services:
  discord-bot:
    image: ghcr.io/contour-gara/home-finance-manager-discord-bot:latest
    environment:
      HOME_FINANCE_MANAGER_BOT_TOKEN: ${HOME_FINANCE_MANAGER_BOT_TOKEN}
      HOME_FINANCE_MANAGER_CHANNEL_ID: ${HOME_FINANCE_MANAGER_CHANNEL_ID}
